### ISSUE TITLE
quarkus-cafe-kitchen fails on build in OpenShift 4.4.3

### ISSUE THREAD

**Issue by tosin2013** [jeremyrdavis/quarkus-cafe-demo#2]
I am using the following ubi image _ubi-quarkus-native-s2i:20.0.0-java11_.
```
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-cafe-kitchen ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /tmp/src/target/test-classes
[INFO] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/KafkaTestUtil.java: Some input files use or override a deprecated API.
[INFO] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/KafkaTestUtil.java: Recompile with -Xlint:deprecation for details.
[INFO] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/BaseTestContainersIT.java: Some input files use unchecked or unsafe operations.
[INFO] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/BaseTestContainersIT.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/domain/KitchenTest.java:[27,30] com.redhat.quarkus.cafe.kitchen.domain.OrderEvent is abstract; cannot be instantiated
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/domain/KitchenTest.java:[29,16] cannot find symbol
  symbol:   method orderIn(com.redhat.quarkus.cafe.kitchen.domain.OrderEvent)
  location: variable kitchen of type com.redhat.quarkus.cafe.kitchen.domain.Kitchen
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/OrderInIT.java:[92,30] com.redhat.quarkus.cafe.kitchen.domain.OrderEvent is abstract; cannot be instantiated
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.287 s
[INFO] Finished at: 2020-05-18T18:59:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project quarkus-cafe-kitchen: Compilation failure: Compilation failure: 
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/domain/KitchenTest.java:[27,30] com.redhat.quarkus.cafe.kitchen.domain.OrderEvent is abstract; cannot be instantiated
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/domain/KitchenTest.java:[29,16] cannot find symbol
[ERROR]   symbol:   method orderIn(com.redhat.quarkus.cafe.kitchen.domain.OrderEvent)
[ERROR]   location: variable kitchen of type com.redhat.quarkus.cafe.kitchen.domain.Kitchen
[ERROR] /tmp/src/src/test/java/com/redhat/quarkus/cafe/kitchen/infrastructure/OrderInIT.java:[92,30] com.redhat.quarkus.cafe.kitchen.domain.OrderEvent is abstract; cannot be instantiated
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project quarkus-cafe-kitchen: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/local/s2i/assemble": exit status 1
```
